apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace:  {{ .Release.Namespace }}
  labels:  {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "payments.dbPassword es requerido" .Values.dbPassword | quote }}
  RABBITMQ_PASSWORD: {{ required "payments.rabbitmqPassword es requerido" .Values.rabbitmqPassword | quote }}
