apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: 
    {{ .Release.Namespace }}
  labels: 
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "gateway.jwtSecret es requerido" .Values.jwtSecret | quote }}