apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "users.dbPassword es requerido" .Values.dbPassword | quote }}
