apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "auth.jwtSecret es requerido" .Values.jwtSecret | quote }}
  DB_PASSWORD: {{ required "auth.dbPassword es requerido" .Values.dbPassword | quote }}
