apiVersion: v1
kind: Secret
metadata:
  name: reservations-secret
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "reservations.dbPassword es requerido" .Values.dbPassword | quote }}
  RABBITMQ_PASSWORD: {{ required "reservations.rabbitmqPassword es requerido" .Values.rabbitmqPassword | quote }}
