apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-reservations
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
