replicaCount: 3

image:
  repository: "rodrigo150604"
  name: "sa-users"
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

