apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgAgH5CS90XUBfn74y0V1f7xdYQ1W9MBHDtTScqIXFqDAf9Gu94a9ayL7r0n9tRRyoQ6r2T4RKgoDss+KWaXKmfvcyES4WW7pw85bPeP+8evPDRb4UOt1pMG8wumqg+8WRqIzGDXKLkByNMMvagMg7KQfPErbxLSrXIXRUmhLvhlOqywhNY7HCljyEbC0RSG9aGKIse4I2uPFGE+JuM+HptTzQ7j03QvTKniebF9iSa9UxB6NUm3YpKVC7mb1wjQTm2QSnCY7q9YIueJiZbqbE0JJvFHsvH/EukW/+Lad2s9BfmhquClmL1NjA7U9JuZoo2Xszi/vpIqg9r+xgKRGKMOoy5ZD0lo3fvfoSfD2fxCwtTvZKcXIJZCGCmVJMFhNnmY8/GYPXpz7jPl1pQsR6SiB9PvQIVpdf6YFkRvWlNlUXyBfHMEWcYaDBgc2uEskoj46tuz0eUuaGcJWR5Di/QrgqrXFl1d2ApWW1SnoLJrMMAdDhjr6xO3lQnzbReN2xDJz4FDrDxgpXn5/sfRoPDZ8UQ9Z+cIt6cyTqggDshfNmqJKq3ooHbD9Z05T94jKo5AZIqJsBrfDDhyu4XWfMhNWGc4RzgPaVa2S4iOiFg066JpfEMckZZbTkTJ329GIfdgkgJGNqnHhgERKrPXd6Qy9QcdMNKGpUS6l9MyEMJITSMixUEc6C52mJkY3uJ6vWe6VdhmhmrTDhXttq0W70ErB/UjTcxsUpCi8Nw3
    username: AgBvBtYa0EG9vdSgyRYS2FFzsbR2BsGC7CMuD8OyKTqqO7R48sFOrPmwNOHgiwLMBMluUQ7FAE7ozLbCjBqsJNer+D2t1SE9LaBihA0k5n0sYcfQ8cixdkhUwiGmR7RNPgRE/lqX11Y758clxhs95qnbbPxAX6l0M6n+q7QBhsipcoWPzBOEHrP9pofqtSvgRKPtiwogkRztMIqMT9/AydaiJ64Rq553czieezcJnlR9Tm5gA3DzjkP1vtDa9JBkRsrS4WwDyznaTRv+RFzI2RduqKyGwUxPjU7WQYT12j2XYQ5nySTYDrApyxR+Zw0s8Bku6HkcYTWsvhrVCxlsBIq9qmbFgFHEQpE0fhhw10uOrsyj6F+RwRxRk9Y/ARGEmHyx54c4aHLmqaVzoAYjM1PbjZks5/MqfU0q3foEu7/4yalZVvwCyxsfrFhRKArG/7vGyY5K720bsuQEDvDmGRQ8S07fHgpBmMkGyIX4m6onOB1G+q+hTQ2mSlwjNcuhivXaNwdT7hlpS8EpsIEi4Xf1ZUWpFoPaxTvlbcGa3/GhRM6feDjr4S9atX2swLN5Mh/Ev73QcexW5KSKRSUjCyTfLG+aPd53iVSQEKGIBURXo4pj/mVs5x8O+L6rJtKc9/D5AJEzbpWNkMnhqWhB1Oo9ChBYWE/2mZcvSVnoJH0PpnjYXt/WJJXKGfVVQq9+e82SAyHrEokv
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: sa-p8
---
