---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: sa-p8
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgBw2QGe/07SHteqtBPNQuU1drrMhhZrS23TH54Lqz3aAWR7fxhbaoaNJOOR55NmoVDjZ5h3JBEYOa+qvhMWzvpxx2/oFAm5ErE5BIp8+A9cDrX4rgi1ywprw6hTTMjdLvbM4vv3+Yp2VTsxgXCqjySciCKhOeuriDVm5s1mv47rr3FIB9Z3VhoxRraTC1Xo3lT4NQy1qFbkB4EIxGJn9fN7TJn7z4UJSmUEayCYwN9jzgGEKbP7ED0KA23Q0NJfxglsdvK5zV52/d+WcH6zHvB167X8Zm6/QV7DlRHroG+S/6itB725qKkTdcfuuEXSzfdzj0WWobPPkdxsZ7inEtg+QXNqKSz7iZdP99YcWpmoQqGvmQXKD/aXkNpurBb3aJKcuG68ulUY1aRRTUAAB4qhPdSxf/gdBmvUQdwtjKB/STt7+4ZCjYbV/GKwcLrhaLLn3PgLuXojeQ5tXI2Jl6rUlgGdjJnnpLUADjhMGpsR6R0f85O3rn+aAwMw+H7xilZncLi2LOMsLAUXT1sCpND7jjMiHjfdB+kICydx8ZgZbh+E3W671MOkzemqA9PHd0s7PMQ8o6afg0A0q6y4pfLByXS+G4FctkG8JWJqenEYlKRxHcCnvm8IiBRGboXEJZ3r7j4rtGRTXzwyK4628YtXSRIMp8ZZgfTDeqJbY8b9AjsfZy635UdTfwVxS2l0cc/WvKHMbjMMbjJdkpVFnk2eQMD8CMUuunwOangVPC2Q1Q==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: sa-p8
