apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secrets
  namespace: sa-p8
spec:
  encryptedData:
    secret: AgBtV7VKKgqUDqK//amp9ru6VZIXahAAhprJouVn45lw7yk6r7XwRpPedyfUXgq7TUxvzEMsGo625cydLQMLXhRD4Jh62NVOJ0kNppl/wJgbZH3CEHERXFvGYwCZDI15obdenbh2Z5Ho2E6AhbI+Bsq5sJYsUK7e2kBL78ZhyHdD/s2R2IhGjuDMUFR8894iyFauDDTPeYUchA6Sv9fqUyXHZ0aquYj/ihDQmW0BgLMmB5DhDEhXef1iUynsXuGQfacS4nFOAWciFR1JHDERrqKVh2jt7WEVQrOlgzYXoiCZA0ByK9OWgMgU0ZscZaH0msm6he2KRNBGmUA5TM4cuqL2yhrFkkWgy05J7/2j+NwzKn6ozh20HnnhCaIqnhq962XkE7pGoV8AnjdfP5gt/qnut+Y8eJyRX1HfmzaLN1ECD8fxr07uHf2EIgHE7HRpCaMKLp2dXgOhLLq2v0W73wwxlcl50H4RkBrbkjZodPifsYmITVwnc8vmdPztQoPOtEIpxlMkbiv3/vFADJojuGHONaVLLWqX60PBtHbmAKYcCw03Q21JhX6W/i9e3Nb3aQ+iBmdptJi85kxl8KqzSVuKZoL7P4UVQQaQA/zQkh5LZxhORNPuyELLoDNJaZwd2MP+Gy8VSb513rmehg57o1QwS41D3LBS1B7tGT/FuSm9FW4qsEMQvdk99iT+Em8IGUM23wt8VAv34944a+aP4fCT3w+ICY4A
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secrets
      namespace: sa-p8
---
