apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials
  namespace: sa-p8
spec:
  encryptedData:
    password: AgAU5DOFxjDx0BWAfa8tDHOoSIC6CfLuXjH0PxZt0SYPQoR3v0Mwh66qaWqdl30NhDLbCUWQLWe9tiR+71gZiNcNxfn18ExAMa208obT4kUFeTi4sXqkKqg9ufdAAlpVXbBR4x8HxkjN5ktVbIC3DtJTtCXRurARtZpXErFVNFePbEz3a6WY+42w3dgE+6160hSS99YByxAo2dChpymUlT7TG+hfkfJgh6gNuH4XQCrRdCyi+S7ssVum78fa+JF521MTPYgHAf2yqlj4yOtZwYWdQnrNC5J0qOobm918lFKVNwpPY3tiOKrOLzwRiVDVMz2gPrehnZ/BGs/3IytIG8bgG6ggzsOut9tbXEsVcYgGdKNms3KNdhwnYc8nQ74SWpLQPbIvMHlk4C+/p9swxhu2FCSC4YaQWQuWutsExg0w1U+pdYJ/sq2fy7AH41G1iweyaUXD4H7JlZDsXTMILzcbvkskHpLwmv0KaVNGK3AJzgnDHn4cbiyYVCYNFEvNPSbZt4Yw1+D3qJO1fXAcP9OdcHjM84U8k4I2TX9undxMAhPO2YiWFCBi2E1cFDynsOPA0UD1So0aXoyIVvrxU7OtLWuE3C4+c/eRhT+1xqf+6yIFZJ3SX7Zis9GUNeL+Tf8Oh+or4JTPWdgRHhPIHws0zUfHBfxVT8cGNGlUk4o/1rlIRqHVVAu+crFvPPrleIQfFvLUj9ApquftQwA3YDY+i7UsT2YhfZM5
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials
      namespace: sa-p8
---
