---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: sa-p8
spec:
  encryptedData:
    DB_PASSWORD: AgCEIRby67Mvv42V77YslZbJ2BpI+JSxG+ita5Lh0ULSpVig9axG6V4IBHTPOZY1HuYWyG/xYeexABz//njHB6N8iCpeU7xT/EK4CwSCD7kq2rUa6BctfY/CUHQOaaOVifyyWZAheEOSLcEzvukK8BRzo9lCsw06ohaLUDTK3AkIT2wISGXicsULEZjft6cxoMGCWyY3eY3aKfGZ7uDrzNraSMqITfmbdB2drd96C81NRPHPgQ4NGP0lRbXVcaxX7rwAUplS7CmAZPpDPZcyLLvL5s7HKhFBXo3kWBUxyL+bYcI7CJ2+zX0YHg9Vd+SiOfNWeI5HIc871qdl4JIBSU/0tWk40h6CQBgMRrLq/syKrto44O8tN4ZpMs/LayETZeEpKworv/W5S73ocWPTOw0fzCyiKyZRBnXTDy+yh5OlDFljzq3neMCXBNAywFxiiKYYnWSsZrg4e356pFpquTZdHg+s9XGkVFpeJUI8S58fWj6vVz6p3RWbzmlisjzw3eTwG+oaoOTGttB3eWSzXcj3nanY/ho6dqm2IjjqvpaByNhuZ3oK0pdoJN9Te1eJvtSWr+95TWg2dBLRug+fLjFLO4q24Qg2DQthseO9kit8DMg2GAHjzqZxjobRSXzL+eTHKHtmle+/JSaR7NCEHTMbo44Fi6pP7kwJL4IAH7mCZ0DoqUmJMTns/Ej1qw0OEwT4FRM/w1dQTkYf+XJ1KDswwFP9hsN42TN9bCara3be
    username: AgBAWTmm1O9AgqiV8b+Cv4MjW6ZcSX14Rbel3g+FhI/IUnG5/ppvBQFU297YUJ2+JMXDfxk6PFeXTcRAF/lWsQYXbku+j9tN1NbCzpG1it1hpwwXqjRwByOBrCXiwdUEh9P5XCgGN8f5z02IOab/H0evEZTU/mZUX/EXBpYkeLqkIvvIhA5cHVAl2+zkMndfkTwrrWdPLuAmeIMdnNGGd34dvotJFW4aVhqewyE0Uc+68747Q1oSJZgcFuu5yQcly3aKh+e1IipwktXsZ7knXFN5LwAD7hh7NwlBqMXqGT6Z9HZkeIIyv9wKY/RwozImnF7b4vDtsRavUL2+RwlaK8sDe1clTCP2Z0E9SCG3rg64SatavXzMeWquwvVSzYG7TBrYyYpcAkUmB3eo0MRLCGLMQKgEXD5uZqhPsOP/QHWS5AY0mdL+TDIbccz+fKYKUNxc0A+s+CvaTAgyQvTcvdCMxAlyZa3hedT3YqSpmfjjr1uZHNy88rjljbnfQ5lGocFmvARUNE2xcF7J0g8up9ulTG3GybbW2q5WJNB/gLf/7Q4q+cLtdXOkz/pBhCMY7DNVbeyHVMgs2GdZRZ87nTo/jyTngv8pxDi7zpRr6nzQauvwTAeDX6tAlcSd60CbgACUqGqCWFbMS+WiGhtCrzXMf7TlmWC+cWTXTyiRpUtTAfEdgg9aTWZSb6K4+EwnSEWAhXD7oWec
  template:
    metadata:
      name: db-credentials
      namespace: sa-p8
