---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secrets
  namespace: sa-p8
spec:
  encryptedData:
    secret: AgCjnuKviVqzwstJpaFzeY+WYgLQK/qzIX5AT9Gn6ICSOC4gLPdJARiap0Z/Nwjiimnm59lJv5VZDGorBGuMzfOjtmf3Fd9gGgv0SLdCTWrtTxdFdq0R5sM2gIbgkThOPGN+cjjsgckFARdBtTROX1q6RzTq8ZtIJe45jzqByy9gF2l0jFDPRLr3ogUSBRKnOb+XpGY72hExiNq17jDfDgzEG1E942AJ5ajCjYLYs0P4IN9MsOh8OlIn3d8PMiNuCAOaIXaeFfWCBFugOt+nratSQzHHx8a9RkZepvgbMVxGEwMWdh3rMyXnxoUy+tti2Xk/LpIOWRi2eiS3bBMMlKkBSi9v9Wxckz+iEh6dItNI/+g78j7IfKhxe+FmUnXDNslQfGuqCM66OwCP/xEcQP/yiw96LCDMcDZwzGGG/nndrlO50j7QhHQVznsLZkROy43lmF979WueE7agB1QCc0+BCfwQVLjEp7zhOK/2JjAQiEtAb9alwgTWij1fJnp/1Y4sGr9OfBs9pXjyBvSYuZgmE9cHhOmQStepZqgFSKg+7tLJwEHUVti5NDwwYg/xR2x12pKgVrzcEE91ZGJyDKqLCZoE6YoXta3oogBkPOJzKZIvLYW7sEJphNi2VIKMhf0ttgdW/NmuWxF2pNA000gYiySUN2stadIKc0fuLw75UxaH8GVHrekFD6DFcHFXwdDAuGrpYXcP5IGk+vS8sDc0tsngYzX39Ve5GxRl2kQf2HtNMnz06Ymc7xsGY28Swm5rJgYS3VALKaDw2k6gGjAG
  template:
    metadata:
      name: jwt-secrets
      namespace: sa-p8
